workspace:
  base: /var/www/owncloud
  path: apps/user_ldap

branches: [master, release*]

pipeline:
  ldap:
    image: dinkel/openldap
    detach: true
    pull: true
    environment:
      - SLAPD_DOMAIN=owncloud.com
      - SLAPD_ORGANIZATION=ownCloud
      - SLAPD_PASSWORD=admin
      - SLAPD_ADDITIONAL_MODULES=memberof

  install-server:
    image: owncloudci/core
    pull: true
    version: ${OC_VERSION}
    db_type: mysql
    db_name: owncloud
    db_host: mysql:3306
    db_username: owncloud
    db_password: owncloud
    when:
      matrix:
        NEED_SERVER: true

  print-log:
    image: owncloudci/php
    detach: true
    commands:
     - tail -f /var/www/owncloud/data/owncloud.log

  install-app:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - cd /var/www/owncloud/apps/user_ldap
      - make
      - cd /var/www/owncloud/
      - php occ a:l
      - php occ a:e user_ldap
      - php occ a:e testing
      - php occ a:l
      - php occ config:system:set trusted_domains 1 --value=server
      - php occ config:system:set trusted_domains 2 --value=federated
      - php occ log:manage --level 0
    when:
      matrix:
        NEED_INSTALL_APP: true

  ldap-config-for-acceptance-tests:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - cd /var/www/owncloud/
      - bash ./apps/user_ldap/tests/acceptance/setConfig.sh
      - php occ ldap:show-config
      - php occ ldap:test-config "LDAPTestId"
      - php occ user:sync "OCA\User_LDAP\User_Proxy" -m remove
      - php occ user:list
    when:
      matrix:
        TEST_SUITE: acceptance

  fix-permissions:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - chown www-data /var/www/owncloud -R
      - chmod 777 /var/www/owncloud/tests/acceptance/filesForUpload -R
      - chmod +x /var/www/owncloud/tests/acceptance/run.sh
    when:
      matrix:
        TEST_SUITE: acceptance

  run-ldap-acceptance-tests:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - BROWSER=chrome #chrome or firefox
      - SELENIUM_HOST=selenium
      - SELENIUM_PORT=4444
      - TEST_SERVER_URL=http://server
      - TEST_SERVER_FED_URL=http://federated
      - PLATFORM=Linux
      - TEST_EXTERNAL_USER_BACKENDS=true
      - BEHAT_SUITE=webUIUserLDAP
    commands:
      - cd /var/www/owncloud/tests/acceptance
      - ./run.sh --config /var/www/owncloud/apps/user_ldap/tests/acceptance/config/behat.yml
    when:
      matrix:
        TEST_SOURCE: ldap

  run-core-webui-tests:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - BROWSER=chrome #chrome or firefox
      - SELENIUM_HOST=selenium
      - SELENIUM_PORT=4444
      - TEST_SERVER_URL=http://server
      - TEST_SERVER_FED_URL=http://federated
      - PLATFORM=Linux
      - TEST_EXTERNAL_USER_BACKENDS=true
      - BEHAT_SUITE=webUICore
    commands:
      - cd /var/www/owncloud/tests/acceptance
      - ./run.sh --remote --config /var/www/owncloud/apps/user_ldap/tests/acceptance/config/behat.yml --tags '@TestAlsoOnExternalUserBackend&&~@skipOnLDAP&&~@skip'
    when:
      matrix:
        TEST_SOURCE: core-webUI

  run-core-api-tests:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - TEST_SERVER_URL=http://server
      - TEST_SERVER_FED_URL=http://federated
      - TEST_EXTERNAL_USER_BACKENDS=true
      - BEHAT_SUITE=${BEHAT_SUITE}
    commands:
      - cd /var/www/owncloud/tests/acceptance
      - ./run.sh --remote --config /var/www/owncloud/apps/user_ldap/tests/acceptance/config/behat.yml --tags '@TestAlsoOnExternalUserBackend&&~@skipOnLDAP&&~@skip'
    when:
      matrix:
        TEST_SOURCE: core-api

  run-integration-tests:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - LDAP_HOST=ldap
    commands:
      - php -f ./tests/integration/Lib/${INTEGRATION_TEST_SCRIPT}
    when:
      matrix:
        TEST_SUITE: integration

  lint-test:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - make test-php-lint
    when:
      matrix:
        TEST_SUITE: lint

  php-cs-fixer:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - make test-php-style
    when:
      matrix:
        TEST_SUITE: lint

  phan:
   image: owncloudci/php:7.1
   pull: true
   commands:
     - make test-php-phan
   when:
     matrix:
       TEST_SUITE: phan

  phpunit-tests:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - cd /var/www/owncloud
      - phpdbg -d memory_limit=4096M -rr ./lib/composer/bin/phpunit --configuration apps/user_ldap/tests/unit/phpunit.xml
    when:
      matrix:
        TEST_SUITE: phpunit

  codecov:
    image: plugins/codecov:2
    secrets: [codecov_token]
    pull: true
    paths:
     - tests/output
    files:
     - '*.xml'
    when:
      matrix:
        TEST_SUITE: phpunit
        PHP_VERSION: 7.1

  notify:
    image: plugins/slack:1
    pull: true
    secrets: [ slack_webhook ]
    channel: builds
    when:
      status: [ failure, changed ]
      event: [ push, tag ]

services:
  server:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - APACHE_WEBROOT=/var/www/owncloud/
    command: [ "/usr/local/bin/apachectl", "-e", "debug" , "-D" , "FOREGROUND" ]
    when:
      matrix:
        TEST_SUITE: acceptance

  federated:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - APACHE_WEBROOT=/var/www/owncloud/
    command: [ "/usr/local/bin/apachectl", "-e", "debug" , "-D" , "FOREGROUND" ]
    when:
      matrix:
        TEST_SUITE: acceptance

  selenium:
    image: selenium/standalone-chrome-debug:latest
    pull: true
    when:
      matrix:
        TEST_SUITE: acceptance

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_USER=owncloud
      - MYSQL_PASSWORD=owncloud
      - MYSQL_DATABASE=owncloud
      - MYSQL_ROOT_PASSWORD=owncloud

matrix:
  include:
#syntax lint check
   - TEST_SUITE: lint
     PHP_VERSION: 7.1
     NEED_SERVER: false
     NEED_INSTALL_APP: false

   - TEST_SUITE: lint
     PHP_VERSION: 5.6
     NEED_SERVER: false
     NEED_INSTALL_APP: false

   - TEST_SUITE: phan
     PHP_VERSION: 7.1
     NEED_SERVER: true
     OC_VERSION: daily-master-qa
     NEED_INSTALL_APP: true

   - TEST_SUITE: phan
     PHP_VERSION: 7.1
     NEED_SERVER: true
     OC_VERSION: daily-stable10-qa
     NEED_INSTALL_APP: true

#unit tests
   - TEST_SUITE: phpunit
     PHP_VERSION: 7.1
     OC_VERSION: daily-master-qa
     NEED_SERVER: true
     NEED_INSTALL_APP: true

   - TEST_SUITE: phpunit
     PHP_VERSION: 7.2
     OC_VERSION: daily-master-qa
     NEED_SERVER: true
     NEED_INSTALL_APP: true

   - TEST_SUITE: phpunit
     PHP_VERSION: 7.2
     OC_VERSION: daily-stable10-qa
     NEED_SERVER: true
     NEED_INSTALL_APP: true

   - TEST_SUITE: phpunit
     PHP_VERSION: 7.1
     OC_VERSION: daily-stable10-qa
     NEED_SERVER: true
     NEED_INSTALL_APP: true
     
   - TEST_SUITE: phpunit
     PHP_VERSION: 7.0
     OC_VERSION: daily-stable10-qa
     NEED_SERVER: true
     NEED_INSTALL_APP: true

   - TEST_SUITE: phpunit
     PHP_VERSION: 5.6
     OC_VERSION: daily-stable10-qa
     NEED_SERVER: true
     NEED_INSTALL_APP: true

#acceptance tests - ldap specific
   - TEST_SUITE: acceptance
     TEST_SOURCE: ldap
     OC_VERSION: daily-master-qa
     PHP_VERSION: 7.1
     NEED_SERVER: true
     NEED_INSTALL_APP: true

   - TEST_SUITE: acceptance
     TEST_SOURCE: ldap
     OC_VERSION: daily-stable10-qa
     PHP_VERSION: 7.0
     NEED_SERVER: true
     NEED_INSTALL_APP: true

   - TEST_SUITE: acceptance
     TEST_SOURCE: ldap
     OC_VERSION: daily-stable10-qa
     PHP_VERSION: 5.6
     NEED_SERVER: true
     NEED_INSTALL_APP: true

#acceptance tests - UI tests from core
   - TEST_SUITE: acceptance
     TEST_SOURCE: core-webUI
     OC_VERSION: daily-master-qa
     PHP_VERSION: 7.1
     NEED_SERVER: true
     NEED_INSTALL_APP: true

   - TEST_SUITE: acceptance
     TEST_SOURCE: core-webUI
     OC_VERSION: daily-stable10-qa
     PHP_VERSION: 7.0
     NEED_SERVER: true
     NEED_INSTALL_APP: true

   - TEST_SUITE: acceptance
     TEST_SOURCE: core-webUI
     OC_VERSION: daily-stable10-qa
     PHP_VERSION: 5.6
     NEED_SERVER: true
     NEED_INSTALL_APP: true

#acceptance tests - API tests from core
   - TEST_SUITE: acceptance
     TEST_SOURCE: core-api
     OC_VERSION: daily-master-qa
     PHP_VERSION: 7.1
     NEED_SERVER: true
     NEED_INSTALL_APP: true
     BEHAT_SUITE: apiMain

   - TEST_SUITE: acceptance
     TEST_SOURCE: core-api
     OC_VERSION: daily-master-qa
     PHP_VERSION: 7.1
     NEED_SERVER: true
     NEED_INSTALL_APP: true
     BEHAT_SUITE: apiMetadataApps

   - TEST_SUITE: acceptance
     TEST_SOURCE: core-api
     OC_VERSION: daily-master-qa
     PHP_VERSION: 7.1
     NEED_SERVER: true
     NEED_INSTALL_APP: true
     BEHAT_SUITE: apiSharees

   - TEST_SUITE: acceptance
     TEST_SOURCE: core-api
     OC_VERSION: daily-master-qa
     PHP_VERSION: 7.1
     NEED_SERVER: true
     NEED_INSTALL_APP: true
     BEHAT_SUITE: apiShareManagement

   - TEST_SUITE: acceptance
     TEST_SOURCE: core-api
     OC_VERSION: daily-master-qa
     PHP_VERSION: 7.1
     NEED_SERVER: true
     NEED_INSTALL_APP: true
     BEHAT_SUITE: apiShareOperations

   - TEST_SUITE: acceptance
     TEST_SOURCE: core-api
     OC_VERSION: daily-master-qa
     PHP_VERSION: 7.1
     NEED_SERVER: true
     NEED_INSTALL_APP: true
     BEHAT_SUITE: apiTrashbin

   - TEST_SUITE: acceptance
     TEST_SOURCE: core-api
     OC_VERSION: daily-master-qa
     PHP_VERSION: 7.1
     NEED_SERVER: true
     NEED_INSTALL_APP: true
     BEHAT_SUITE: apiSharingNotifications

   - TEST_SUITE: acceptance
     TEST_SOURCE: core-api
     OC_VERSION: daily-master-qa
     PHP_VERSION: 7.1
     NEED_SERVER: true
     NEED_INSTALL_APP: true
     BEHAT_SUITE: apiWebdavOperations

   - TEST_SUITE: acceptance
     TEST_SOURCE: core-api
     OC_VERSION: daily-master-qa
     PHP_VERSION: 7.1
     NEED_SERVER: true
     NEED_INSTALL_APP: true
     BEHAT_SUITE: apiWebdavProperties

   - TEST_SUITE: acceptance
     TEST_SOURCE: core-api
     OC_VERSION: daily-stable10-qa
     PHP_VERSION: 7.0
     NEED_SERVER: true
     NEED_INSTALL_APP: true
     BEHAT_SUITE: apiMain

   - TEST_SUITE: acceptance
     TEST_SOURCE: core-api
     OC_VERSION: daily-stable10-qa
     PHP_VERSION: 7.0
     NEED_SERVER: true
     NEED_INSTALL_APP: true
     BEHAT_SUITE: apiMetadataApps

   - TEST_SUITE: acceptance
     TEST_SOURCE: core-api
     OC_VERSION: daily-stable10-qa
     PHP_VERSION: 7.0
     NEED_SERVER: true
     NEED_INSTALL_APP: true
     BEHAT_SUITE: apiSharees

   - TEST_SUITE: acceptance
     TEST_SOURCE: core-api
     OC_VERSION: daily-stable10-qa
     PHP_VERSION: 7.0
     NEED_SERVER: true
     NEED_INSTALL_APP: true
     BEHAT_SUITE: apiShareManagement

   - TEST_SUITE: acceptance
     TEST_SOURCE: core-api
     OC_VERSION: daily-stable10-qa
     PHP_VERSION: 7.0
     NEED_SERVER: true
     NEED_INSTALL_APP: true
     BEHAT_SUITE: apiShareOperations

   - TEST_SUITE: acceptance
     TEST_SOURCE: core-api
     OC_VERSION: daily-stable10-qa
     PHP_VERSION: 7.0
     NEED_SERVER: true
     NEED_INSTALL_APP: true
     BEHAT_SUITE: apiTrashbin

   - TEST_SUITE: acceptance
     TEST_SOURCE: core-api
     OC_VERSION: daily-stable10-qa
     PHP_VERSION: 7.0
     NEED_SERVER: true
     NEED_INSTALL_APP: true
     BEHAT_SUITE: apiSharingNotifications

   - TEST_SUITE: acceptance
     TEST_SOURCE: core-api
     OC_VERSION: daily-stable10-qa
     PHP_VERSION: 7.0
     NEED_SERVER: true
     NEED_INSTALL_APP: true
     BEHAT_SUITE: apiWebdavOperations

   - TEST_SUITE: acceptance
     TEST_SOURCE: core-api
     OC_VERSION: daily-stable10-qa
     PHP_VERSION: 7.0
     NEED_SERVER: true
     NEED_INSTALL_APP: true
     BEHAT_SUITE: apiWebdavProperties

   - TEST_SUITE: acceptance
     TEST_SOURCE: core-api
     OC_VERSION: daily-stable10-qa
     PHP_VERSION: 5.6
     NEED_SERVER: true
     NEED_INSTALL_APP: true
     BEHAT_SUITE: apiMain

   - TEST_SUITE: acceptance
     TEST_SOURCE: core-api
     OC_VERSION: daily-stable10-qa
     PHP_VERSION: 5.6
     NEED_SERVER: true
     NEED_INSTALL_APP: true
     BEHAT_SUITE: apiMetadataApps

   - TEST_SUITE: acceptance
     TEST_SOURCE: core-api
     OC_VERSION: daily-stable10-qa
     PHP_VERSION: 5.6
     NEED_SERVER: true
     NEED_INSTALL_APP: true
     BEHAT_SUITE: apiSharees

   - TEST_SUITE: acceptance
     TEST_SOURCE: core-api
     OC_VERSION: daily-stable10-qa
     PHP_VERSION: 5.6
     NEED_SERVER: true
     NEED_INSTALL_APP: true
     BEHAT_SUITE: apiShareManagement

   - TEST_SUITE: acceptance
     TEST_SOURCE: core-api
     OC_VERSION: daily-stable10-qa
     PHP_VERSION: 5.6
     NEED_SERVER: true
     NEED_INSTALL_APP: true
     BEHAT_SUITE: apiShareOperations

   - TEST_SUITE: acceptance
     TEST_SOURCE: core-api
     OC_VERSION: daily-stable10-qa
     PHP_VERSION: 5.6
     NEED_SERVER: true
     NEED_INSTALL_APP: true
     BEHAT_SUITE: apiTrashbin

   - TEST_SUITE: acceptance
     TEST_SOURCE: core-api
     OC_VERSION: daily-stable10-qa
     PHP_VERSION: 5.6
     NEED_SERVER: true
     NEED_INSTALL_APP: true
     BEHAT_SUITE: apiSharingNotifications

   - TEST_SUITE: acceptance
     TEST_SOURCE: core-api
     OC_VERSION: daily-stable10-qa
     PHP_VERSION: 5.6
     NEED_SERVER: true
     NEED_INSTALL_APP: true
     BEHAT_SUITE: apiWebdavOperations

   - TEST_SUITE: acceptance
     TEST_SOURCE: core-api
     OC_VERSION: daily-stable10-qa
     PHP_VERSION: 5.6
     NEED_SERVER: true
     NEED_INSTALL_APP: true
     BEHAT_SUITE: apiWebdavProperties
#integration tests
   - TEST_SUITE: integration
     OC_VERSION: daily-master-qa
     PHP_VERSION: 7.1
     INTEGRATION_TEST_SCRIPT: IntegrationTestAccessGroupsMatchFilter.php
     NEED_SERVER: true
     NEED_INSTALL_APP: true

   - TEST_SUITE: integration
     OC_VERSION: daily-master-qa
     PHP_VERSION: 7.1
     INTEGRATION_TEST_SCRIPT: IntegrationBackupServer.php
     NEED_SERVER: true
     NEED_INSTALL_APP: true

   - TEST_SUITE: integration
     OC_VERSION: daily-master-qa
     PHP_VERSION: 7.1
     INTEGRATION_TEST_SCRIPT: User/IntegrationTestUserAvatar.php
     NEED_SERVER: true
     NEED_INSTALL_APP: true

   - TEST_SUITE: integration
     OC_VERSION: daily-master-qa
     PHP_VERSION: 7.1
     INTEGRATION_TEST_SCRIPT: User/IntegrationTestUserDisplayName.php
     NEED_SERVER: true
     NEED_INSTALL_APP: true

   - TEST_SUITE: integration
     OC_VERSION: daily-master-qa
     PHP_VERSION: 7.1
     INTEGRATION_TEST_SCRIPT: IntegrationTestBackupServer.php
     NEED_SERVER: true
     NEED_INSTALL_APP: true

   - TEST_SUITE: integration
     OC_VERSION: daily-master-qa
     PHP_VERSION: 7.1
     INTEGRATION_TEST_SCRIPT: IntegrationConnect.php
     NEED_SERVER: true
     NEED_INSTALL_APP: true

   - TEST_SUITE: integration
     OC_VERSION: daily-master-qa
     PHP_VERSION: 7.1
     INTEGRATION_TEST_SCRIPT: IntegrationTestBatchApplyUserAttributes.php
     NEED_SERVER: true
     NEED_INSTALL_APP: true

   - TEST_SUITE: integration
     OC_VERSION: daily-master-qa
     PHP_VERSION: 7.1
     INTEGRATION_TEST_SCRIPT: IntegrationTestConnect.php
     NEED_SERVER: true
     NEED_INSTALL_APP: true

   - TEST_SUITE: integration
     OC_VERSION: daily-master-qa
     PHP_VERSION: 7.1
     INTEGRATION_TEST_SCRIPT: IntegrationTestCountUsersByLoginName.php
     NEED_SERVER: true
     NEED_INSTALL_APP: true

   - TEST_SUITE: integration
     OC_VERSION: daily-master-qa
     PHP_VERSION: 7.1
     INTEGRATION_TEST_SCRIPT: IntegrationTestFetchUsersByLoginName.php
     NEED_SERVER: true
     NEED_INSTALL_APP: true

   - TEST_SUITE: integration
     OC_VERSION: daily-master-qa
     PHP_VERSION: 7.1
     INTEGRATION_TEST_SCRIPT: IntegrationTestPaging.php
     NEED_SERVER: true
     NEED_INSTALL_APP: true

   - TEST_SUITE: integration
     OC_VERSION: daily-stable10-qa
     PHP_VERSION: 5.6
     INTEGRATION_TEST_SCRIPT: IntegrationTestAccessGroupsMatchFilter.php
     NEED_SERVER: true
     NEED_INSTALL_APP: true

   - TEST_SUITE: integration
     OC_VERSION: daily-stable10-qa
     PHP_VERSION: 5.6
     INTEGRATION_TEST_SCRIPT: IntegrationBackupServer.php
     NEED_SERVER: true
     NEED_INSTALL_APP: true

   - TEST_SUITE: integration
     OC_VERSION: daily-stable10-qa
     PHP_VERSION: 5.6
     INTEGRATION_TEST_SCRIPT: User/IntegrationTestUserAvatar.php
     NEED_SERVER: true
     NEED_INSTALL_APP: true

   - TEST_SUITE: integration
     OC_VERSION: daily-stable10-qa
     PHP_VERSION: 5.6
     INTEGRATION_TEST_SCRIPT: User/IntegrationTestUserDisplayName.php
     NEED_SERVER: true
     NEED_INSTALL_APP: true

   - TEST_SUITE: integration
     OC_VERSION: daily-stable10-qa
     PHP_VERSION: 5.6
     INTEGRATION_TEST_SCRIPT: IntegrationTestBackupServer.php
     NEED_SERVER: true
     NEED_INSTALL_APP: true

   - TEST_SUITE: integration
     OC_VERSION: daily-stable10-qa
     PHP_VERSION: 5.6
     INTEGRATION_TEST_SCRIPT: IntegrationConnect.php
     NEED_SERVER: true
     NEED_INSTALL_APP: true

   - TEST_SUITE: integration
     OC_VERSION: daily-stable10-qa
     PHP_VERSION: 5.6
     INTEGRATION_TEST_SCRIPT: IntegrationTestBatchApplyUserAttributes.php
     NEED_SERVER: true
     NEED_INSTALL_APP: true

   - TEST_SUITE: integration
     OC_VERSION: daily-stable10-qa
     PHP_VERSION: 5.6
     INTEGRATION_TEST_SCRIPT: IntegrationTestConnect.php
     NEED_SERVER: true
     NEED_INSTALL_APP: true

   - TEST_SUITE: integration
     OC_VERSION: daily-stable10-qa
     PHP_VERSION: 5.6
     INTEGRATION_TEST_SCRIPT: IntegrationTestCountUsersByLoginName.php
     NEED_SERVER: true
     NEED_INSTALL_APP: true

   - TEST_SUITE: integration
     OC_VERSION: daily-stable10-qa
     PHP_VERSION: 5.6
     INTEGRATION_TEST_SCRIPT: IntegrationTestFetchUsersByLoginName.php
     NEED_SERVER: true
     NEED_INSTALL_APP: true

   - TEST_SUITE: integration
     OC_VERSION: daily-stable10-qa
     PHP_VERSION: 5.6
     INTEGRATION_TEST_SCRIPT: IntegrationTestPaging.php
     NEED_SERVER: true
     NEED_INSTALL_APP: true
