---
kind: pipeline
type: docker
name: coding-standard-php7.1

platform:
  os: linux
  arch: amd64

workspace:
  base: /var/www/owncloud
  path: server/apps/user_ldap

steps:
- name: coding-standard
  pull: always
  image: owncloudci/php:7.1
  commands:
  - make test-php-style

trigger:
  ref:
  - refs/pull/**
  - refs/tags/**
  - refs/heads/master

---
kind: pipeline
type: docker
name: phan-php7.1

platform:
  os: linux
  arch: amd64

workspace:
  base: /var/www/owncloud
  path: server/apps/user_ldap

steps:
- name: install-core
  pull: always
  image: owncloudci/core
  settings:
    core_path: /var/www/owncloud/server
    db_host: sqlite
    db_name: owncloud
    db_password: owncloud
    db_type: sqlite
    db_username: owncloud
    exclude: apps/user_ldap
    version: daily-master-qa

- name: phan
  pull: always
  image: owncloudci/php:7.1
  commands:
  - make test-php-phan

trigger:
  ref:
  - refs/pull/**
  - refs/tags/**
  - refs/heads/master

---
kind: pipeline
type: docker
name: phan-php7.2

platform:
  os: linux
  arch: amd64

workspace:
  base: /var/www/owncloud
  path: server/apps/user_ldap

steps:
- name: install-core
  pull: always
  image: owncloudci/core
  settings:
    core_path: /var/www/owncloud/server
    db_host: sqlite
    db_name: owncloud
    db_password: owncloud
    db_type: sqlite
    db_username: owncloud
    exclude: apps/user_ldap
    version: daily-master-qa

- name: phan
  pull: always
  image: owncloudci/php:7.2
  commands:
  - make test-php-phan

trigger:
  ref:
  - refs/pull/**
  - refs/tags/**
  - refs/heads/master

---
kind: pipeline
type: docker
name: phan-php7.3

platform:
  os: linux
  arch: amd64

workspace:
  base: /var/www/owncloud
  path: server/apps/user_ldap

steps:
- name: install-core
  pull: always
  image: owncloudci/core
  settings:
    core_path: /var/www/owncloud/server
    db_host: sqlite
    db_name: owncloud
    db_password: owncloud
    db_type: sqlite
    db_username: owncloud
    exclude: apps/user_ldap
    version: daily-master-qa

- name: phan
  pull: always
  image: owncloudci/php:7.3
  commands:
  - make test-php-phan

trigger:
  ref:
  - refs/pull/**
  - refs/tags/**
  - refs/heads/master

---
kind: pipeline
type: docker
name: phpunit-php7.2-mysql5.7

platform:
  os: linux
  arch: amd64

workspace:
  base: /var/www/owncloud
  path: server/apps/user_ldap

steps:
- name: install-core
  pull: always
  image: owncloudci/core
  settings:
    core_path: /var/www/owncloud/server
    db_host: mysql
    db_name: owncloud
    db_password: owncloud
    db_type: mysql
    db_username: owncloud
    exclude: apps/user_ldap
    version: daily-master-qa

- name: setup-server-user_ldap
  pull: always
  image: owncloudci/php:7.2
  commands:
  - cd /var/www/owncloud/server
  - php occ a:l
  - php occ a:e user_ldap
  - php occ a:e testing
  - php occ a:l
  - php occ config:system:set trusted_domains 1 --value=server
  - php occ log:manage --level 2

- name: phpunit-tests
  pull: always
  image: owncloudci/php:7.2
  commands:
  - make test-php-unit

services:
- name: mysql
  pull: always
  image: mysql:5.7
  environment:
    MYSQL_DATABASE: owncloud
    MYSQL_PASSWORD: owncloud
    MYSQL_ROOT_PASSWORD: owncloud
    MYSQL_USER: owncloud

trigger:
  ref:
  - refs/pull/**
  - refs/tags/**
  - refs/heads/master

depends_on:
- coding-standard-php7.1
- phan-php7.1
- phan-php7.2
- phan-php7.3

---
kind: pipeline
type: docker
name: apiProvisioningLDAP-master-mysql5.7-php7.3

platform:
  os: linux
  arch: amd64

workspace:
  base: /var/www/owncloud
  path: testrunner/apps/user_ldap

steps:
- name: install-core
  pull: always
  image: owncloudci/core
  settings:
    core_path: /var/www/owncloud/server
    db_host: mysql
    db_name: owncloud
    db_password: owncloud
    db_type: mysql
    db_username: owncloud
    exclude: apps/user_ldap
    version: daily-master-qa

- name: install-testrunner
  pull: always
  image: owncloudci/php:7.3
  commands:
  - mkdir /tmp/testrunner
  - git clone -b master --depth=1 https://github.com/owncloud/core.git /tmp/testrunner
  - rsync -aIX /tmp/testrunner /var/www/owncloud
  - cp -r /var/www/owncloud/testrunner/apps/user_ldap /var/www/owncloud/server/apps/

- name: setup-server-user_ldap
  pull: always
  image: owncloudci/php:7.3
  commands:
  - cd /var/www/owncloud/server
  - php occ a:l
  - php occ a:e user_ldap
  - php occ a:e testing
  - php occ a:l
  - php occ config:system:set trusted_domains 1 --value=server
  - php occ log:manage --level 2

- name: owncloud-log-server
  pull: always
  image: owncloud/ubuntu:18.04
  detach: true
  commands:
  - tail -f /var/www/owncloud/server/data/owncloud.log

- name: configure-app
  pull: always
  image: owncloudci/php:7.1
  commands:
  - cd /var/www/owncloud/server
  - bash ./apps/user_ldap/tests/acceptance/setConfig.sh
  - php occ ldap:show-config
  - php occ ldap:test-config "LDAPTestId"
  - php occ user:sync "OCA\User_LDAP\User_Proxy" -m remove
  - php occ user:list

- name: fix-permissions
  pull: always
  image: owncloudci/php:7.3
  commands:
  - chown -R www-data /var/www/owncloud/server
  - wait-for-it -t 600 server:80

- name: acceptance-tests
  pull: always
  image: owncloudci/php:7.3
  commands:
  - touch /var/www/owncloud/saved-settings.sh
  - . /var/www/owncloud/saved-settings.sh
  - make test-acceptance-api
  environment:
    BEHAT_SUITE: apiProvisioningLDAP
    TEST_EXTERNAL_USER_BACKENDS: true
    TEST_SERVER_URL: http://server

services:
- name: mysql
  pull: always
  image: mysql:5.7
  environment:
    MYSQL_DATABASE: owncloud
    MYSQL_PASSWORD: owncloud
    MYSQL_ROOT_PASSWORD: owncloud
    MYSQL_USER: owncloud

- name: ldap
  pull: always
  image: osixia/openldap
  environment:
    HOSTNAME: ldap
    LDAP_ADMIN_PASSWORD: admin
    LDAP_DOMAIN: owncloud.com
    LDAP_ORGANISATION: owncloud
    LDAP_TLS_VERIFY_CLIENT: never

- name: server
  pull: always
  image: owncloudci/php:7.3
  commands:
  - /usr/local/bin/apachectl -e debug -D FOREGROUND
  environment:
    APACHE_WEBROOT: /var/www/owncloud/server

trigger:
  ref:
  - refs/pull/**
  - refs/tags/**
  - refs/heads/master

depends_on:
- coding-standard-php7.1
- phan-php7.1
- phan-php7.2
- phan-php7.3

---
kind: pipeline
type: docker
name: apiUserLDAP-master-mysql5.7-php7.3

platform:
  os: linux
  arch: amd64

workspace:
  base: /var/www/owncloud
  path: testrunner/apps/user_ldap

steps:
- name: install-core
  pull: always
  image: owncloudci/core
  settings:
    core_path: /var/www/owncloud/server
    db_host: mysql
    db_name: owncloud
    db_password: owncloud
    db_type: mysql
    db_username: owncloud
    exclude: apps/user_ldap
    version: daily-master-qa

- name: install-testrunner
  pull: always
  image: owncloudci/php:7.3
  commands:
  - mkdir /tmp/testrunner
  - git clone -b master --depth=1 https://github.com/owncloud/core.git /tmp/testrunner
  - rsync -aIX /tmp/testrunner /var/www/owncloud
  - cp -r /var/www/owncloud/testrunner/apps/user_ldap /var/www/owncloud/server/apps/

- name: setup-server-user_ldap
  pull: always
  image: owncloudci/php:7.3
  commands:
  - cd /var/www/owncloud/server
  - php occ a:l
  - php occ a:e user_ldap
  - php occ a:e testing
  - php occ a:l
  - php occ config:system:set trusted_domains 1 --value=server
  - php occ log:manage --level 2

- name: owncloud-log-server
  pull: always
  image: owncloud/ubuntu:18.04
  detach: true
  commands:
  - tail -f /var/www/owncloud/server/data/owncloud.log

- name: configure-app
  pull: always
  image: owncloudci/php:7.1
  commands:
  - cd /var/www/owncloud/server
  - bash ./apps/user_ldap/tests/acceptance/setConfig.sh
  - php occ ldap:show-config
  - php occ ldap:test-config "LDAPTestId"
  - php occ user:sync "OCA\User_LDAP\User_Proxy" -m remove
  - php occ user:list

- name: fix-permissions
  pull: always
  image: owncloudci/php:7.3
  commands:
  - chown -R www-data /var/www/owncloud/server
  - wait-for-it -t 600 server:80

- name: acceptance-tests
  pull: always
  image: owncloudci/php:7.3
  commands:
  - touch /var/www/owncloud/saved-settings.sh
  - . /var/www/owncloud/saved-settings.sh
  - make test-acceptance-api
  environment:
    BEHAT_SUITE: apiUserLDAP
    TEST_EXTERNAL_USER_BACKENDS: true
    TEST_SERVER_URL: http://server

services:
- name: mysql
  pull: always
  image: mysql:5.7
  environment:
    MYSQL_DATABASE: owncloud
    MYSQL_PASSWORD: owncloud
    MYSQL_ROOT_PASSWORD: owncloud
    MYSQL_USER: owncloud

- name: ldap
  pull: always
  image: osixia/openldap
  environment:
    HOSTNAME: ldap
    LDAP_ADMIN_PASSWORD: admin
    LDAP_DOMAIN: owncloud.com
    LDAP_ORGANISATION: owncloud
    LDAP_TLS_VERIFY_CLIENT: never

- name: server
  pull: always
  image: owncloudci/php:7.3
  commands:
  - /usr/local/bin/apachectl -e debug -D FOREGROUND
  environment:
    APACHE_WEBROOT: /var/www/owncloud/server

trigger:
  ref:
  - refs/pull/**
  - refs/tags/**
  - refs/heads/master

depends_on:
- coding-standard-php7.1
- phan-php7.1
- phan-php7.2
- phan-php7.3

---
kind: pipeline
type: docker
name: chat-notifications

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: notify-rocketchat
  pull: always
  image: plugins/slack:1
  settings:
    channel: builds
    webhook:
      from_secret: private_rocketchat

trigger:
  ref:
  - refs/tags/**
  - refs/heads/master
  status:
  - success
  - failure

depends_on:
- phpunit-php7.2-mysql5.7
- apiProvisioningLDAP-master-mysql5.7-php7.3
- apiUserLDAP-master-mysql5.7-php7.3

...
