workspace:
  base: /var/www/owncloud
  path: apps/user_ldap

branches: [master, release*, release/*]

pipeline:
  ldap:
    image: dinkel/openldap
    detach: true
    pull: true
    environment:
      - SLAPD_DOMAIN=owncloud.com
      - SLAPD_ORGANIZATION=ownCloud
      - SLAPD_PASSWORD=admin
      - SLAPD_ADDITIONAL_MODULES=memberof
    commands:
      - /entrypoint.sh
      - slapadd -F /etc/ldap/slapd.d -l /var/www/owncloud/apps/user_ldap/tests/acceptance/config/ldap-users.ldif
      - chown -R openldap:openldap /etc/ldap/slapd.d/ /var/lib/ldap/ /var/run/slapd/
      - slapd -d 32768 -u openldap -g openldap
    when:
      matrix:
        NEED_PRELOAD_USER: true

  ldap:
    image: dinkel/openldap
    detach: true
    pull: true
    environment:
      - SLAPD_DOMAIN=owncloud.com
      - SLAPD_ORGANIZATION=ownCloud
      - SLAPD_PASSWORD=admin
      - SLAPD_ADDITIONAL_MODULES=memberof
    when:
      matrix:
        NEED_PRELOAD_USER: false

  install-server:
    image: owncloudci/core
    pull: true
    version: ${OC_VERSION}
    db_type: mysql
    db_name: owncloud
    db_host: mysql:3306
    db_username: owncloud
    db_password: owncloud
    when:
      matrix:
        NEED_SERVER: true

  install-app:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - cd /var/www/owncloud/apps/user_ldap
      - make
      - cd /var/www/owncloud/
      - php occ a:l
      - php occ a:e user_ldap
      - php occ a:e testing
      - php occ a:l
      - php occ config:system:set trusted_domains 1 --value=server
      - php occ config:system:set trusted_domains 2 --value=federated
      - php occ log:manage --level 0
    when:
      matrix:
        NEED_INSTALL_APP: true

  ldap-config-for-acceptance-tests:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - cd /var/www/owncloud/
      - bash ./apps/user_ldap/tests/acceptance/setConfig.sh
      - php occ ldap:show-config
      - php occ ldap:test-config "LDAPTestId"
      - php occ user:sync "OCA\User_LDAP\User_Proxy" -m remove
    when:
      matrix:
        TEST_SUITE: acceptance

  run-ldap-acceptance-tests:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - BROWSER=chrome #chrome or firefox
      - SELENIUM_HOST=selenium
      - SRV_HOST_NAME=server
      - SRV_HOST_PORT=80
      - REMOTE_FED_SRV_HOST_NAME=federated
      - REMOTE_FED_SRV_HOST_PORT=80
      - SKELETON_DIR=/var/www/owncloud/tests/acceptance/webUISkeleton
      - SELENIUM_PORT=4444
      - PLATFORM=Linux
      - TEST_EXTERNAL_USER_BACKENDS=true
    commands:
      - cd /var/www/owncloud
      - chown www-data * -R
      - chmod 777 /var/www/owncloud/tests/acceptance/filesForUpload -R
      - bash tests/travis/start_ui_tests.sh --config apps/user_ldap/tests/acceptance/config/behat.yml
    when:
      matrix:
        TEST_SOURCE: ldap

  run-core-acceptance-tests:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - BROWSER=chrome #chrome or firefox
      - SELENIUM_HOST=selenium
      - SRV_HOST_NAME=server
      - SRV_HOST_PORT=80
      - REMOTE_FED_SRV_HOST_NAME=federated
      - REMOTE_FED_SRV_HOST_PORT=80
      - SKELETON_DIR=/var/www/owncloud/tests/acceptance/webUISkeleton
      - SELENIUM_PORT=4444
      - PLATFORM=Linux
      - TEST_EXTERNAL_USER_BACKENDS=true
    commands:
      - cd /var/www/owncloud
      - chown www-data * -R
      - chmod 777 /var/www/owncloud/tests/acceptance/filesForUpload -R
      - bash tests/travis/start_ui_tests.sh --remote --tags '@TestAlsoOnExternalUserBackend&&~@skipOnLDAP'
    when:
      matrix:
        TEST_SOURCE: core

  run-integration-tests:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - LDAP_HOST=ldap
    commands:
      - php -f ./tests/integration/Lib/${INTEGRATION_TEST_SCRIPT}
    when:
      matrix:
        TEST_SUITE: integration

  lint-test:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - cd /var/www/owncloud/apps/user_ldap
      - make
      - vendor/bin/parallel-lint  --exclude vendor .
    when:
      matrix:
        TEST_SUITE: lint

  phpunit-tests:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - cd /var/www/owncloud
      - phpdbg -d memory_limit=4096M -rr ./lib/composer/bin/phpunit --configuration apps/user_ldap/tests/unit/phpunit.xml
    when:
      matrix:
        TEST_SUITE: phpunit

  codecov:
    image: plugins/codecov:2
    secrets: [codecov_token]
    pull: true
    paths:
     - tests/output
    files:
     - '*.xml'
    when:
      matrix:
        TEST_SUITE: phpunit
        PHP_VERSION: 7.1

  owncloud-log:
    image: owncloud/ubuntu:16.04
    pull: true
    commands:
      - cat /var/www/owncloud/data/owncloud.log
    when:
      status: [ failure ]

  notify:
    image: plugins/slack:1
    pull: true
    secrets: [ slack_webhook ]
    channel: builds
    when:
      status: [ failure, changed ]
      event: [ push, tag ]

services:
  server:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - APACHE_WEBROOT=/var/www/owncloud/
    command: [ "/usr/local/bin/apachectl", "-e", "debug" , "-D" , "FOREGROUND" ]
    when:
      matrix:
        TEST_SUITE: acceptance

  federated:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - APACHE_WEBROOT=/var/www/owncloud/
    command: [ "/usr/local/bin/apachectl", "-e", "debug" , "-D" , "FOREGROUND" ]
    when:
      matrix:
        TEST_SUITE: acceptance

  selenium:
    image: selenium/standalone-chrome-debug:latest
    pull: true
    when:
      matrix:
        TEST_SUITE: acceptance

  mysql:
    image: mysql:5.5
    environment:
      - MYSQL_USER=owncloud
      - MYSQL_PASSWORD=owncloud
      - MYSQL_DATABASE=owncloud
      - MYSQL_ROOT_PASSWORD=owncloud

matrix:
  include:
#syntax lint check
   - TEST_SUITE: lint
     PHP_VERSION: 7.1
     NEED_SERVER: false
     NEED_INSTALL_APP: false
   - TEST_SUITE: lint
     PHP_VERSION: 5.6
     NEED_SERVER: false
     NEED_INSTALL_APP: false
     
#unit tests
   - TEST_SUITE: phpunit
     PHP_VERSION: 7.1
     OC_VERSION: daily-master-qa
     NEED_SERVER: true
     NEED_INSTALL_APP: true
     
   - TEST_SUITE: phpunit
     PHP_VERSION: 7.0
     OC_VERSION: daily-stable10-qa
     NEED_SERVER: true
     NEED_INSTALL_APP: true

   - TEST_SUITE: phpunit
     PHP_VERSION: 5.6
     OC_VERSION: daily-stable10-qa
     NEED_SERVER: true
     NEED_INSTALL_APP: true

#acceptance tests
   - TEST_SUITE: acceptance
     TEST_SOURCE: ldap
     OC_VERSION: daily-master-qa
     PHP_VERSION: 7.1
     NEED_SERVER: true
     NEED_INSTALL_APP: true
     NEED_PRELOAD_USER: false

   - TEST_SUITE: acceptance
     TEST_SOURCE: ldap
     OC_VERSION: daily-stable10-qa
     PHP_VERSION: 7.0
     NEED_SERVER: true
     NEED_INSTALL_APP: true
     NEED_PRELOAD_USER: false

   - TEST_SUITE: acceptance
     TEST_SOURCE: ldap
     OC_VERSION: daily-stable10-qa
     PHP_VERSION: 5.6
     NEED_SERVER: true
     NEED_INSTALL_APP: true
     NEED_PRELOAD_USER: false

   - TEST_SUITE: acceptance
     TEST_SOURCE: core
     OC_VERSION: daily-master-qa
     PHP_VERSION: 7.1
     NEED_SERVER: true
     NEED_INSTALL_APP: true
     NEED_PRELOAD_USER: true

   - TEST_SUITE: acceptance
     TEST_SOURCE: core
     OC_VERSION: daily-stable10-qa
     PHP_VERSION: 7.0
     NEED_SERVER: true
     NEED_INSTALL_APP: true
     NEED_PRELOAD_USER: true

   - TEST_SUITE: acceptance
     TEST_SOURCE: core
     OC_VERSION: daily-stable10-qa
     PHP_VERSION: 5.6
     NEED_SERVER: true
     NEED_INSTALL_APP: true
     NEED_PRELOAD_USER: true

#integration tests
   - TEST_SUITE: integration
     OC_VERSION: daily-master-qa
     PHP_VERSION: 7.1
     INTEGRATION_TEST_SCRIPT: IntegrationTestAccessGroupsMatchFilter.php
     NEED_SERVER: true
     NEED_INSTALL_APP: true
     NEED_PRELOAD_USER: false

   - TEST_SUITE: integration
     OC_VERSION: daily-master-qa
     PHP_VERSION: 7.1
     INTEGRATION_TEST_SCRIPT: IntegrationBackupServer.php
     NEED_SERVER: true
     NEED_INSTALL_APP: true
     NEED_PRELOAD_USER: false

   - TEST_SUITE: integration
     OC_VERSION: daily-master-qa
     PHP_VERSION: 7.1
     INTEGRATION_TEST_SCRIPT: User/IntegrationTestUserAvatar.php
     NEED_SERVER: true
     NEED_INSTALL_APP: true
     NEED_PRELOAD_USER: false

   - TEST_SUITE: integration
     OC_VERSION: daily-master-qa
     PHP_VERSION: 7.1
     INTEGRATION_TEST_SCRIPT: User/IntegrationTestUserDisplayName.php
     NEED_SERVER: true
     NEED_INSTALL_APP: true
     NEED_PRELOAD_USER: false

   - TEST_SUITE: integration
     OC_VERSION: daily-master-qa
     PHP_VERSION: 7.1
     INTEGRATION_TEST_SCRIPT: IntegrationTestBackupServer.php
     NEED_SERVER: true
     NEED_INSTALL_APP: true
     NEED_PRELOAD_USER: false

   - TEST_SUITE: integration
     OC_VERSION: daily-master-qa
     PHP_VERSION: 7.1
     INTEGRATION_TEST_SCRIPT: IntegrationConnect.php
     NEED_SERVER: true
     NEED_INSTALL_APP: true
     NEED_PRELOAD_USER: false

   - TEST_SUITE: integration
     OC_VERSION: daily-master-qa
     PHP_VERSION: 7.1
     INTEGRATION_TEST_SCRIPT: IntegrationTestBatchApplyUserAttributes.php
     NEED_SERVER: true
     NEED_INSTALL_APP: true
     NEED_PRELOAD_USER: false

   - TEST_SUITE: integration
     OC_VERSION: daily-master-qa
     PHP_VERSION: 7.1
     INTEGRATION_TEST_SCRIPT: IntegrationTestConnect.php
     NEED_SERVER: true
     NEED_INSTALL_APP: true
     NEED_PRELOAD_USER: false

   - TEST_SUITE: integration
     OC_VERSION: daily-master-qa
     PHP_VERSION: 7.1
     INTEGRATION_TEST_SCRIPT: IntegrationTestCountUsersByLoginName.php
     NEED_SERVER: true
     NEED_INSTALL_APP: true
     NEED_PRELOAD_USER: false

   - TEST_SUITE: integration
     OC_VERSION: daily-master-qa
     PHP_VERSION: 7.1
     INTEGRATION_TEST_SCRIPT: IntegrationTestFetchUsersByLoginName.php
     NEED_SERVER: true
     NEED_INSTALL_APP: true
     NEED_PRELOAD_USER: false

   - TEST_SUITE: integration
     OC_VERSION: daily-master-qa
     PHP_VERSION: 7.1
     INTEGRATION_TEST_SCRIPT: IntegrationTestPaging.php
     NEED_SERVER: true
     NEED_INSTALL_APP: true
     NEED_PRELOAD_USER: false

   - TEST_SUITE: integration
     OC_VERSION: daily-stable10-qa
     PHP_VERSION: 5.6
     INTEGRATION_TEST_SCRIPT: IntegrationTestAccessGroupsMatchFilter.php
     NEED_SERVER: true
     NEED_INSTALL_APP: true
     NEED_PRELOAD_USER: false

   - TEST_SUITE: integration
     OC_VERSION: daily-stable10-qa
     PHP_VERSION: 5.6
     INTEGRATION_TEST_SCRIPT: IntegrationBackupServer.php
     NEED_SERVER: true
     NEED_INSTALL_APP: true
     NEED_PRELOAD_USER: false

   - TEST_SUITE: integration
     OC_VERSION: daily-stable10-qa
     PHP_VERSION: 5.6
     INTEGRATION_TEST_SCRIPT: User/IntegrationTestUserAvatar.php
     NEED_SERVER: true
     NEED_INSTALL_APP: true
     NEED_PRELOAD_USER: false

   - TEST_SUITE: integration
     OC_VERSION: daily-stable10-qa
     PHP_VERSION: 5.6
     INTEGRATION_TEST_SCRIPT: User/IntegrationTestUserDisplayName.php
     NEED_SERVER: true
     NEED_INSTALL_APP: true
     NEED_PRELOAD_USER: false

   - TEST_SUITE: integration
     OC_VERSION: daily-stable10-qa
     PHP_VERSION: 5.6
     INTEGRATION_TEST_SCRIPT: IntegrationTestBackupServer.php
     NEED_SERVER: true
     NEED_INSTALL_APP: true
     NEED_PRELOAD_USER: false

   - TEST_SUITE: integration
     OC_VERSION: daily-stable10-qa
     PHP_VERSION: 5.6
     INTEGRATION_TEST_SCRIPT: IntegrationConnect.php
     NEED_SERVER: true
     NEED_INSTALL_APP: true
     NEED_PRELOAD_USER: false

   - TEST_SUITE: integration
     OC_VERSION: daily-stable10-qa
     PHP_VERSION: 5.6
     INTEGRATION_TEST_SCRIPT: IntegrationTestBatchApplyUserAttributes.php
     NEED_SERVER: true
     NEED_INSTALL_APP: true
     NEED_PRELOAD_USER: false

   - TEST_SUITE: integration
     OC_VERSION: daily-stable10-qa
     PHP_VERSION: 5.6
     INTEGRATION_TEST_SCRIPT: IntegrationTestConnect.php
     NEED_SERVER: true
     NEED_INSTALL_APP: true
     NEED_PRELOAD_USER: false

   - TEST_SUITE: integration
     OC_VERSION: daily-stable10-qa
     PHP_VERSION: 5.6
     INTEGRATION_TEST_SCRIPT: IntegrationTestCountUsersByLoginName.php
     NEED_SERVER: true
     NEED_INSTALL_APP: true
     NEED_PRELOAD_USER: false

   - TEST_SUITE: integration
     OC_VERSION: daily-stable10-qa
     PHP_VERSION: 5.6
     INTEGRATION_TEST_SCRIPT: IntegrationTestFetchUsersByLoginName.php
     NEED_SERVER: true
     NEED_INSTALL_APP: true
     NEED_PRELOAD_USER: false

   - TEST_SUITE: integration
     OC_VERSION: daily-stable10-qa
     PHP_VERSION: 5.6
     INTEGRATION_TEST_SCRIPT: IntegrationTestPaging.php
     NEED_SERVER: true
     NEED_INSTALL_APP: true
     NEED_PRELOAD_USER: false
