workspace:
  base: /var/www/owncloud
  path: apps/user_ldap

pipeline:
  ldap:
    image: dinkel/openldap
    detach: true
    pull: true
    environment:
      - SLAPD_DOMAIN=owncloud.com
      - SLAPD_ORGANIZATION=ownCloud
      - SLAPD_PASSWORD=admin
      - SLAPD_ADDITIONAL_MODULES=memberof
    commands:
      - /entrypoint.sh
      - slapadd -F /etc/ldap/slapd.d -l /var/www/owncloud/apps/user_ldap/tests/acceptance/ldap-users.ldif
      - slapd -d 32768 -u openldap -g openldap

  install-server:
    image: arturneumann/owncloud-ci-php:latest
    pull: true
    commands:
      - cd /var/www
      - wget -q http://172.17.0.1/owncloud-daily/owncloud-daily-master-qa-patched.tar.bz2
      - tar -xjf owncloud-daily-master-qa-patched.tar.bz2
      - cd /var/www/owncloud/
      - php occ maintenance:install -vvv --database=sqlite --database-name=owncloud --database-table-prefix=oc_ --admin-user=admin --admin-pass=admin --data-dir=/var/www/owncloud/data
      - cd /var/www/owncloud/apps/user_ldap
      - make
      - cd /var/www/owncloud/
      - php occ a:l
      - php occ a:e user_ldap
      - php occ a:e testing
      - php occ a:l
      - php occ config:system:set trusted_domains 1 --value=owncloud
      - php occ log:manage --level 0
      - bash ./apps/user_ldap/tests/acceptance/setConfig.sh
      - php occ ldap:show-config
      - php occ ldap:test-config "LDAPTestId"
      - php occ user:sync "OCA\User_LDAP\User_Proxy" -m remove

  owncloud-log:
    image: owncloud/ubuntu:16.04
    detach: true
    pull: true
    commands:
      - tail -f /var/www/owncloud/data/owncloud.log

  run-tests:
    image: arturneumann/owncloud-ci-php:latest
    pull: true
    environment:
      - BROWSER=chrome #chrome or firefox
      - SELENIUM_HOST=selenium
      - SRV_HOST_NAME=owncloud
      - SRV_HOST_PORT=80
      - SKELETON_DIR=/var/www/owncloud/tests/ui/skeleton
      - SELENIUM_PORT=4444
      - PLATFORM=Linux
    commands:
      - cd /var/www/owncloud
      - chown www-data * -R
      - chmod +x lib/composer/behat/behat/bin/behat
      - rm lib/composer/bin/behat
      - ln -s ../behat/behat/bin/behat lib/composer/bin/behat
      - chmod 777 /var/www/owncloud/tests/ui/filesForUpload -R
      - bash tests/travis/start_ui_tests.sh --remote --tags @LDAP --feature /var/www/owncloud/tests/ui/features/other/login.feature:12

services:
  owncloud:
    image: arturneumann/owncloud-ci-php:latest
    pull: true
    environment:
      - APACHE_WEBROOT=/var/www/owncloud/
    command: [ "/usr/local/bin/apachectl", "-e debug" , "-DFOREGROUND" ]

  selenium:
    image: selenium/standalone-chrome-debug:latest
    pull: true
  

      
