configID="LDAPTestId"
./occ ldap:delete-config $configID
./occ ldap:create-empty-config $configID
./occ ldap:set-config  "$configID" ldapAgentName                 "cn=admin,dc=owncloud,dc=com"
./occ ldap:set-config  "$configID" ldapAgentPassword             "admin"
./occ ldap:set-config  "$configID" ldapBase                      "dc=owncloud,dc=com"
./occ ldap:set-config  "$configID" ldapBaseGroups                "dc=owncloud,dc=com"
./occ ldap:set-config  "$configID" ldapBaseUsers                 "dc=owncloud,dc=com"
./occ ldap:set-config  "$configID" ldapEmailAttribute            "mail"
./occ ldap:set-config  "$configID" ldapExpertUUIDUserAttr        "uid"
./occ ldap:set-config  "$configID" ldapGroupDisplayName          "cn"
./occ ldap:set-config  "$configID" ldapGroupFilter               "(&(|(objectclass=posixGroup)))"
./occ ldap:set-config  "$configID" ldapGroupFilterObjectclass    "posixGroup"
./occ ldap:set-config  "$configID" ldapGroupMemberAssocAttr      "memberUid"
./occ ldap:set-config  "$configID" ldapHost                      "ldap"
./occ ldap:set-config  "$configID" ldapLoginFilter               "(&(|(objectclass=inetOrgPerson))(|(uid=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid))))"
./occ ldap:set-config  "$configID" ldapLoginFilterEmail          "1"
./occ ldap:set-config  "$configID" ldapLoginFilterMode           "0"
./occ ldap:set-config  "$configID" ldapLoginFilterUsername       "1"
./occ ldap:set-config  "$configID" ldapNestedGroups              "0"
./occ ldap:set-config  "$configID" ldapPagingSize                "500"
./occ ldap:set-config  "$configID" ldapPort                      "389"
./occ ldap:set-config  "$configID" ldapTLS                       "0"
./occ ldap:set-config  "$configID" ldapUserDisplayName           "displayName"
./occ ldap:set-config  "$configID" ldapUserFilter                "(|(objectclass=inetOrgPerson))"
./occ ldap:set-config  "$configID" ldapUserFilterMode            "0"
./occ ldap:set-config  "$configID" ldapUserFilterObjectclass     "inetOrgPerson"
./occ ldap:set-config  "$configID" ldapUuidGroupAttribute        "auto"
./occ ldap:set-config  "$configID" ldapUuidUserAttribute         "auto"
./occ ldap:set-config  "$configID" turnOffCertCheck              "0"
./occ ldap:set-config  "$configID" useMemberOfToDetectMembership "1"

